### ISSUE TITLE
pod does not integrate as a framework

### ISSUE THREAD

**Issue by niewiemek** [bennyguitar/Colours#42]
The library does not work when we use use_frameworks! in our Podfile

http://blog.cocoapods.org/CocoaPods-0.36/

**Comment by greuff** [comment]
+1

**Comment by sammyGain** [comment]
+1

**Comment by sammyGain** [comment]
Anybody find a workaround yet :disappointed:

**Comment by bennyguitar** [comment]
I'm looking into doing this - but the general documentation online makes it easy for non-library creators to use frameworks, but I'm not exactly sure how to make it as an owner so that you can use them in your apps. Any links?

**Comment by bennyguitar** [comment]
When I run `pod lib lint --use-libraries Colours.podspec` from the main Colours directory, it passes validation, though I don't know if this means that frameworks are working successfully. This information comes from http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/ which shows that I should be using `--use-frameworks` as an argument, but that fails because it's not an option.

**Comment by bennyguitar** [comment]
This issue is now resolved. Use `5.11.0` or higher, and make sure your podfile looks like so:

`pod 'Colours/Swift'` to use the swift subspec.
